export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  deltaApiKey: process.env.DELTA_API_KEY ?? "",
  deltaApiSecret: process.env.DELTA_API_SECRET ?? "",
  deltaBaseUrl: (process.env.DELTA_BASE_URL ?? "https://api.india.delta.exchange").replace(/\/$/, ""),
  deltaMode: process.env.TMT_MODE ?? "paper",
  liveTradingEnabled: process.env.TMT_LIVE_TRADING_ENABLED === "true",
  liveTradingAcknowledgement: process.env.TMT_LIVE_TRADING_ACK ?? "",
  liveTradingAcknowledgementPhrase: "I_ACCEPT_LIVE_ORDER_RISK",
  liveLots: Number(process.env.TMT_LIVE_LOTS ?? "0"),
  maxLiveLots: Number(process.env.TMT_MAX_LIVE_LOTS ?? "0"),
  nativeBracketsEnabled: process.env.TMT_NATIVE_BRACKETS_ENABLED === "true",
  workerPollSeconds: Math.max(5, Number(process.env.TMT_WATCHDOG_POLL_SECONDS ?? "5")),
  ownerWebhookUrl: process.env.OWNER_WEBHOOK_URL ?? "",
  localAuthAllowRegistration: process.env.TMT_AUTH_ALLOW_REGISTRATION !== "false",
  localSessionDays: Math.min(30, Math.max(1, Number(process.env.TMT_LOCAL_SESSION_DAYS ?? "7"))),
  credentialEncryptionKey: process.env.TMT_CREDENTIAL_ENCRYPTION_KEY ?? "",
};
